# ============================================================
# Create input sensitivities that fix growth (VB), natural mortality (M),
# or both by changing MFCL estimation switches in doitall.sh.
#
# This step intentionally edits doitall.sh rather than .par. Any copied .par
# and indepvar.rpt files are removed because the fixed/free parameter mapping
# is changed and should be regenerated by the model run.
# ============================================================

source("tools/input_sensitivities/helpers.R")
source("tools/input_change_metadata.R")

normalize_fixed_params <- function(x) {
  vals <- unlist(strsplit(as.character(x), "[,;[:space:]+]+", perl = TRUE), use.names = FALSE)
  vals <- toupper(trimws(vals))
  vals <- vals[nzchar(vals)]
  vals <- sub("^GROWTH$", "VB", vals)
  vals <- sub("^NATURALMORTALITY$", "M", vals)
  vals <- sub("^NATURAL_MORTALITY$", "M", vals)
  vals <- sub("^FIXM$", "M", vals)
  vals <- sub("^FIXVB$", "VB", vals)
  vals <- sub("^FIXVBM$", "VBM", vals)
  if ("VBM" %in% vals || "VBANDM" %in% vals) vals <- c(vals, "VB", "M")
  vals <- vals[vals %in% c("VB", "M")]
  unique(vals)
}

switch_lines_to_zero <- function(lines, switch_ids) {
  changes <- data.frame(
    switch = character(0),
    line = integer(0),
    old = character(0),
    new = character(0),
    stringsAsFactors = FALSE
  )

  for (switch_id in as.character(switch_ids)) {
    pattern <- paste0("^(\\s*1\\s+", switch_id, "\\s+)([-+]?[0-9.]+)(\\s*(#.*)?)$")
    hits <- grepl(pattern, lines, perl = TRUE)
    if (!any(hits)) next
    hit_idx <- which(hits)
    captures <- regmatches(lines[hits], regexec(pattern, lines[hits], perl = TRUE))
    old_values <- vapply(captures, `[[`, character(1), 3L)
    lines[hits] <- vapply(captures, function(x) paste0(x[[2]], "0", x[[4]]), character(1))
    changes <- rbind(
      changes,
      data.frame(
        switch = switch_id,
        line = hit_idx,
        old = old_values,
        new = "0",
        stringsAsFactors = FALSE
      )
    )
  }

  list(lines = lines, changes = changes)
}

apply_fixed_parameter_switches <- function(doitall_path, fixed_groups) {
  lines <- readLines(doitall_path, warn = FALSE)
  switch_ids <- character(0)
  if ("M" %in% fixed_groups) switch_ids <- c(switch_ids, "121")
  if ("VB" %in% fixed_groups) switch_ids <- c(switch_ids, "12", "13", "14")
  switch_ids <- unique(switch_ids)

  result <- switch_lines_to_zero(lines, switch_ids)
  changed_switches <- unique(result$changes$switch)
  missing_switches <- setdiff(switch_ids, changed_switches)
  if (length(missing_switches) > 0) {
    stop(
      "Could not find required MFCL switch(es) in ", doitall_path, ": ",
      paste(missing_switches, collapse = ", ")
    )
  }

  writeLines(result$lines, doitall_path, useBytes = TRUE)
  result$changes
}

fixed_token_and_label <- function(fixed_groups) {
  has_vb <- "VB" %in% fixed_groups
  has_m <- "M" %in% fixed_groups
  if (has_vb && has_m) {
    return(list(token = c("fixM", "fixVB"), label = "Natural mortality (M) and growth (VB) fixed"))
  }
  if (has_vb) return(list(token = "fixVB", label = "Growth (VB) parameters fixed"))
  if (has_m) return(list(token = "fixM", label = "Natural mortality (M) fixed"))
  stop("No fixed parameter group selected.")
}

fixed_suffix <- function(fixed_groups) {
  has_vb <- "VB" %in% fixed_groups
  has_m <- "M" %in% fixed_groups
  if (has_m && has_vb) return("_fixM_fixVB")
  if (has_m) return("_fixM")
  if (has_vb) return("_fixVB")
  ""
}

project_root <- getwd()
inputs_root <- env_or_default("inputs_root", "mfcl/inputs")
single_base_dir <- env_or_default("base_dir", "")
single_out_dir <- env_or_default("out_dir", "")
fixed_params_arg <- env_or_default("fixed_params", env_or_default("fixed_parameter_groups", ""))

fixed_groups <- normalize_fixed_params(fixed_params_arg)
if (length(fixed_groups) == 0) stop("fixed_params is empty. Use M, VB, or VB,M.")

suffix <- {
  fixed_suffix(fixed_groups)
}

dirs <- resolve_single_or_batch_dirs(
  inputs_root = inputs_root,
  base_dir = single_base_dir,
  out_dir = single_out_dir,
  suffix = suffix,
  project_root = project_root
)
source_dirs <- dirs$source_dirs
target_dirs <- dirs$target_dirs

created <- character(0)
for (idx in seq_along(source_dirs)) {
  source_dir <- source_dirs[[idx]]
  target_dir <- target_dirs[[idx]]
  copy_input_dir(source_dir, target_dir)

  removed_par_files <- remove_input_par_files(target_dir)
  stale_indepvar <- file.path(target_dir, "indepvar.rpt")
  removed_indepvar <- file.exists(stale_indepvar)
  if (removed_indepvar) unlink(stale_indepvar, force = TRUE)

  doitall_path <- file.path(target_dir, "doitall.sh")
  if (!file.exists(doitall_path)) stop("No doitall.sh found in ", target_dir)

  switch_change <- apply_fixed_parameter_switches(doitall_path, fixed_groups)
  token_label <- fixed_token_and_label(fixed_groups)
  change_meta <- append_input_change_metadata(
    target_dir,
    token = token_label$token,
    label = token_label$label,
    operation = "fixed_parameters",
    source_dir = source_dir,
    details = list(
      fixed_groups = fixed_groups,
      switches_zeroed = switch_change,
      par_files_removed = basename(removed_par_files),
      indepvar_removed = removed_indepvar
    )
  )

  info <- list(
    source_dir = source_dir,
    created_at = Sys.time(),
    input_change_tokens = change_meta$tokens,
    fixed_groups = fixed_groups,
    switches_zeroed = switch_change,
    modified_file = "doitall.sh",
    par_files_removed = length(removed_par_files) > 0,
    indepvar_removed = removed_indepvar
  )
  saveRDS(info, file = file.path(target_dir, "fixed_parameters_info.rds"), compress = "xz")

  created <- c(created, target_dir)
}

cat("Created fixed-parameter sensitivities:\n")
cat(paste0("  ", created, collapse = "\n"), "\n")
cat("Fixed groups:", paste(fixed_groups, collapse = ", "), "\n")
