name: Test MFCL Model and Build PDF

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  check-changes:
    runs-on: ubuntu-22.04
    outputs:
      model: ${{ steps.changes.outputs.model }}
      report: ${{ steps.changes.outputs.report }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            model:
              - '*.qmd'
            report:
              - 'report/*.qmd'
      
      - name: Debug - Show what changed
        run: |
          echo "Model files changed: ${{ steps.changes.outputs.model }}"
          echo "Report files changed: ${{ steps.changes.outputs.report }}"
          echo "Changed files:"
          echo "${{ steps.changes.outputs.changes }}"

  test-model:
    runs-on: ubuntu-22.04
    needs: check-changes
    if: ${{ needs.check-changes.outputs.model == 'true' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run MFCL model test
      run: make docker-run
      timeout-minutes: 60
    
    - name: Upload model outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mfcl-outputs-${{ github.sha }}
        path: |
          output/
          logs/
          plots/
        retention-days: 30
    
    - name: Generate plots
      if: success()
      run: make docker-plot
    
    - name: Upload generated plots
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mfcl-plots-${{ github.sha }}
        path: plot/plots.html
        retention-days: 90

  build-pdf:
    runs-on: ubuntu-22.04
    needs: check-changes
    if: ${{ needs.check-changes.outputs.report == 'true' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build PDF report  
      run: make docker-report
      timeout-minutes: 30
    
    - name: Debug - Check generated files
      run: |
        echo "=== Report directory contents ==="
        ls -la report/
        find . -name "*.pdf" -type f
        echo "=== File sizes ==="
        du -h report/*.pdf || echo "No PDF files found"

    - name: Upload PDF artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: pdf-report-${{ github.sha }}
        path: report/bet-2026.pdf
        retention-days: 90
