name: Test MFCL Model and Generate Plots

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  check-changes:
    runs-on: ubuntu-22.04
    outputs:
      model: ${{ steps.changes.outputs.model }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            model:
              - '**'
              - '!report/**'
              - '!README.md'
              - '!.github/**'
      
      - name: Debug - Show what changed
        run: |
          echo "Model files changed: ${{ steps.changes.outputs.model }}"

  test-model:
    runs-on: ubuntu-22.04
    needs: check-changes
    if: ${{ needs.check-changes.outputs.model == 'true' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run MFCL model test
      run: make docker-run
      timeout-minutes: 60
    
    - name: Upload model outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mfcl-outputs-${{ github.sha }}
        path: |
          model/
        retention-days: 30
    
    - name: Generate plots
      if: success()
      run: make docker-plot
      timeout-minutes: 30
    
    - name: Upload generated plots
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mfcl-plots-${{ github.sha }}
        path: plot/plots.html
        retention-days: 90
